# Generated by Django 4.2.10 on 2024-03-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_remove_exercisebook_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisebook',
            name='image',
            field=models.ImageField(default='boat.png', upload_to='exercise_images/'),
            preserve_default=False,
        ),
    ]
