# Generated by Django 4.2.10 on 2024-03-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodbook',
            name='image',
            field=models.ImageField(default='grocery.jpeg', upload_to='food_images/'),
            preserve_default=False,
        ),
    ]
