# Generated by Django 4.1 on 2024-03-04 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_interaction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='date_time',
        ),
    ]
